name: CI

on:
  pull_request:
  push:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        experimental: [true, false]

    outputs:
      fail: ${{ steps.test.outputs.fail }}

    steps:
      - name: Check that passes
        run: exit 0

      - name: Check that fails during experimental builds
        if: matrix.experimental
        id: test
        run: |
          echo "::set-output name=fail::true"
          exit 1

  nightly-warning:
    name: Change status of test check
    runs-on: ubuntu-latest
    needs: test
    if: needs.test.outputs.fail

    steps:
      - name: Create failure warning
        uses: actions/github-script@v3
        with:
          script: |
            const checkSuiteId = await github.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            }).check_suite_id

            console.log(checkSuiteId)

            const checkSuite = await github.checks.getSuite({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_suite_id: checkSuiteId,
            })

            console.log(checkSuite)

