name: CI

on:
  pull_request:
  push:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        version: ['1', 'nightly']

    outputs:
      fail: ${{ steps.test.outputs.fail }}

    steps:
      - name: Check that passes
        run: exit 0

      - name: Check that fails during experimental builds
        if: matrix.version == 'nightly'
        id: test
        run: |
          echo "::set-output name=fail::true"
          exit 1

  nightly-warning:
    name: Change status of test check
    runs-on: ubuntu-latest
    needs: test
    if: needs.test.outputs.fail

    steps:
      - name: Create failure warning
        uses: actions/github-script@v3
        with:
          script: |
            const workflowRun = (await github.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            })).data.check_suite_id

            github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'nightly-failures',
              head_sha: context.sha,
              status: 'completed',
              conclusion: 'neutral',
              output: {
                title: 'CI',
                summary: 'Build failures on nightly',
                text: 'There were build failures when using nightly Julia.'
              }
            })

