name: CI

on:
  pull_request:
  push:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        experimental: [true, false]

    outputs:
      fail: ${{ steps.test.outputs.fail }}

    steps:
      - name: Check that passes
        run: exit 0

      - name: Check that fails during experimental builds
        id: test
        run: ${{ matrix.experimental }} && (echo "::set-output name=fail::true"; exit 1)
        continue-on-error: ${{ matrix.experimental }}

  nightly-warning:
    name: Change status of test check
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Create failure warning
        if: needs.test.outputs.fail
        uses: actions/github-script@v3
        with:
          script: |
            const check_suite_id = octokit.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.run_id,
            })//.check_suite_id

            console.log(check_suite_id)

